//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gosei.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeQualification
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int QualificationId { get; set; }
        public string Institution { get; set; }
        public string City { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> ValidFrom { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Note { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
